name: LMTEST
favicon: null
layout_spectrum: 0.2745021227747202
typography_spectrum: 0.7623564053792506
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.3950215559452772
  lightness: 0.4044628569390625
  saturation: 0.6151760946959257
  rhythmicContrast: 0.17521594348363578
purpose: []
